### ISSUE TITLE
add some contact info to the landing page

### ISSUE THREAD

**Issue by pjking07** [pillarlabs/ministry.careers#2]
One or both of our names, or we need to create a generic account.

**Comment by chriskrycho** [comment]
Do we have an existing group for e.g. contact@ministry.careers?

**Comment by chriskrycho** [comment]
We did not have a catch-all address for this kind of thing. I have created one. Sometime in the next week or two I will add the info to the contact page.

**Comment by pjking07** [comment]
:+1:
